// <auto-generated />
using System;
using GenomiX.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GenomiX.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GenomiX.Infrastructure.Models.Answer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Primary key (GUID).");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit")
                        .HasComment("Indicates whether the answer is correct.");

                    b.Property<Guid?>("QuestionId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("FK to Question.");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasComment("Answer text/value.");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Answers", t =>
                        {
                            t.HasComment("Answer option for a Test, with correctness flag.");
                        });
                });

            modelBuilder.Entity("GenomiX.Infrastructure.Models.DNAModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Primary key (GUID).");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasComment("UTC created timestamp.");

                    b.Property<int>("CurrentIndex")
                        .HasColumnType("int")
                        .HasComment("Active timeline index (zero-based).");

                    b.Property<byte>("DisplayMode")
                        .HasColumnType("tinyint")
                        .HasComment("0 = Basic shapes, 1 = Scientific atomic view.");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasComment("UTC updated timestamp.");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Owner user (FK).");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("DNA_Models", t =>
                        {
                            t.HasComment("Editable DNA model holding references to two strand snapshots (double-helix).");
                        });
                });

            modelBuilder.Entity("GenomiX.Infrastructure.Models.DNAModelDisease", b =>
                {
                    b.Property<Guid>("DNA_Model_Id")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("FK to DNAModel.");

                    b.Property<Guid>("DiseaseId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("FK to Disease.");

                    b.Property<Guid?>("DNAModelId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DNA_Model_Id", "DiseaseId");

                    b.HasIndex("DNAModelId");

                    b.HasIndex("DiseaseId");

                    b.ToTable("DNA_Models_Diseases", t =>
                        {
                            t.HasComment("Many-to-many link between DNA models and diseases.");
                        });
                });

            modelBuilder.Entity("GenomiX.Infrastructure.Models.DNAModelMutation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Primary key (GUID).");

                    b.Property<string>("Alt")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasComment("Alternate bases inserted/replacing ref ('' allowed for deletion).");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasComment("UTC timestamp of the mutation record.");

                    b.Property<Guid?>("ModelId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("FK to DNAModel.");

                    b.Property<int>("PosEnd")
                        .HasColumnType("int")
                        .HasComment("1-based inclusive end position in the strand (>= PosStart).");

                    b.Property<int>("PosStart")
                        .HasColumnType("int")
                        .HasComment("1-based inclusive start position in the strand.");

                    b.Property<string>("Ref")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasComment("Reference bases being replaced/removed ('' allowed for insertion).");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasComment("Type of mutation: substitution | insertion | deletion.");

                    b.HasKey("Id");

                    b.HasIndex("ModelId");

                    b.ToTable("DNA_Model_Mutations", t =>
                        {
                            t.HasComment("Atomic edit to a DNAModel (substitution|insertion|deletion).");
                        });
                });

            modelBuilder.Entity("GenomiX.Infrastructure.Models.DNASequence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Primary key (GUID).");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasComment("UTC timestamp when the snapshot was created.");

                    b.Property<Guid>("ModelId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Owning DNAModel (FK).");

                    b.Property<string>("Sequence")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Raw uppercase DNA string (A,C,G,T only).");

                    b.HasKey("Id");

                    b.HasIndex("ModelId");

                    b.ToTable("DNA_Sequences", t =>
                        {
                            t.HasComment("Immutable snapshot of a DNA sequence (A/C/G/T only).");
                        });
                });

            modelBuilder.Entity("GenomiX.Infrastructure.Models.Disease", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Primary key (GUID).");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)")
                        .HasComment("Optional description or summary.");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasComment("Disease name.");

                    b.HasKey("Id");

                    b.ToTable("Diseases", t =>
                        {
                            t.HasComment("Catalog of known diseases.");
                        });
                });

            modelBuilder.Entity("GenomiX.Infrastructure.Models.GenUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("GenomiX.Infrastructure.Models.Lesson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Primary key (GUID).");

                    b.Property<byte>("Difficulty")
                        .HasColumnType("tinyint")
                        .HasComment("Difficulty from 1 to 5.");

                    b.Property<string>("Information")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Markdown/HTML/plain content.");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("Lesson title.");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Topic (mutations, repair, probability, ...).");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("User who created the lesson.");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Lessons", t =>
                        {
                            t.HasComment("Lesson content for Education panel.");
                        });
                });

            modelBuilder.Entity("GenomiX.Infrastructure.Models.Organism", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Primary key (GUID).");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasComment("UTC created timestamp.");

                    b.Property<Guid?>("DNA_Sequence_Id")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("FK to a DNA strand snapshot (for this organism).");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("Optional description.");

                    b.Property<Guid?>("PopulationId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("FK to Population.");

                    b.Property<string>("ScientificName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasComment("Scientific-like identifier.");

                    b.Property<string>("SimpleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Simple/UI name.");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasComment("Status: alive | dead | reproduced.");

                    b.Property<double?>("SurvivalScore")
                        .HasColumnType("float")
                        .HasComment("Continuous survival/fitness score (nullable).");

                    b.HasKey("Id");

                    b.HasIndex("DNA_Sequence_Id");

                    b.HasIndex("PopulationId");

                    b.ToTable("Organisms");
                });

            modelBuilder.Entity("GenomiX.Infrastructure.Models.Population", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Primary key (GUID).");

                    b.Property<Guid?>("BaseModelId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Optional link to the base DNAModel used to derive this population.");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasComment("UTC created timestamp.");

                    b.Property<string>("Factors")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasComment("JSON with simulation factors (temperature, sunExposure, diseasePressure, ...).");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("Human-friendly name for the run.");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("User who created the population.");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Populations", t =>
                        {
                            t.HasComment("A population of organisms simulated under given environmental/selection factors.");
                        });
                });

            modelBuilder.Entity("GenomiX.Infrastructure.Models.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Primary key (GUID).");

                    b.Property<string>("Explanation")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)")
                        .HasComment("Optional explanation or hint for the question.");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasComment("The question text/prompt.");

                    b.Property<Guid?>("TestId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("FK to Test.");

                    b.HasKey("Id");

                    b.HasIndex("TestId");

                    b.ToTable("Questions", t =>
                        {
                            t.HasComment("Question belonging to a Test, with prompt and possible answers.");
                        });
                });

            modelBuilder.Entity("GenomiX.Infrastructure.Models.ReferenceSequence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Primary key (GUID).");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasComment("UTC timestamp when the reference sequence was created.");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("Descriptive name for the reference sequence (e.g., Beta-globin fragment).");

                    b.Property<int>("PairIndex")
                        .HasColumnType("int")
                        .HasComment("Pair index groups complementary strands together (e.g., 0 = initial pair).");

                    b.Property<string>("Sequence")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Raw uppercase DNA string (A,C,G,T only).");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Species or organism identifier for the reference sequence (e.g., Human, Mouse, Dog).");

                    b.Property<byte>("Strand")
                        .HasColumnType("tinyint")
                        .HasComment("Strand index of the reference sequence (1 = forward, 2 = complementary).");

                    b.HasKey("Id");

                    b.ToTable("Reference_Sequences", t =>
                        {
                            t.HasComment("Reference DNA sequence template (e.g., Human, Mouse, Dog). Not tied to a user.");
                        });
                });

            modelBuilder.Entity("GenomiX.Infrastructure.Models.Test", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Primary key (GUID).");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("FK to Lesson.");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasComment("The question text/prompt.");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasComment("Question type: mcq | multi | open.");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.ToTable("Tests", t =>
                        {
                            t.HasComment("Test/quiz question associated with a Lesson.");
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("GenomiX.Infrastructure.Models.Answer", b =>
                {
                    b.HasOne("GenomiX.Infrastructure.Models.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("GenomiX.Infrastructure.Models.DNAModel", b =>
                {
                    b.HasOne("GenomiX.Infrastructure.Models.GenUser", "User")
                        .WithMany("DNAModels")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GenomiX.Infrastructure.Models.DNAModelDisease", b =>
                {
                    b.HasOne("GenomiX.Infrastructure.Models.DNAModel", null)
                        .WithMany("DNAModelDiseases")
                        .HasForeignKey("DNAModelId");

                    b.HasOne("GenomiX.Infrastructure.Models.Disease", null)
                        .WithMany("DNAModelDiseases")
                        .HasForeignKey("DiseaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GenomiX.Infrastructure.Models.DNAModelMutation", b =>
                {
                    b.HasOne("GenomiX.Infrastructure.Models.DNAModel", "Model")
                        .WithMany("Mutations")
                        .HasForeignKey("ModelId");

                    b.Navigation("Model");
                });

            modelBuilder.Entity("GenomiX.Infrastructure.Models.DNASequence", b =>
                {
                    b.HasOne("GenomiX.Infrastructure.Models.DNAModel", "Model")
                        .WithMany("Sequences")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Model");
                });

            modelBuilder.Entity("GenomiX.Infrastructure.Models.Lesson", b =>
                {
                    b.HasOne("GenomiX.Infrastructure.Models.GenUser", "User")
                        .WithMany("Lessons")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GenomiX.Infrastructure.Models.Organism", b =>
                {
                    b.HasOne("GenomiX.Infrastructure.Models.DNASequence", "DNASequence")
                        .WithMany()
                        .HasForeignKey("DNA_Sequence_Id");

                    b.HasOne("GenomiX.Infrastructure.Models.Population", "Population")
                        .WithMany("Organisms")
                        .HasForeignKey("PopulationId");

                    b.Navigation("DNASequence");

                    b.Navigation("Population");
                });

            modelBuilder.Entity("GenomiX.Infrastructure.Models.Population", b =>
                {
                    b.HasOne("GenomiX.Infrastructure.Models.GenUser", "User")
                        .WithMany("Populations")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GenomiX.Infrastructure.Models.Question", b =>
                {
                    b.HasOne("GenomiX.Infrastructure.Models.Test", "Test")
                        .WithMany("Questions")
                        .HasForeignKey("TestId");

                    b.Navigation("Test");
                });

            modelBuilder.Entity("GenomiX.Infrastructure.Models.Test", b =>
                {
                    b.HasOne("GenomiX.Infrastructure.Models.Lesson", null)
                        .WithMany("Tests")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("GenomiX.Infrastructure.Models.GenUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("GenomiX.Infrastructure.Models.GenUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GenomiX.Infrastructure.Models.GenUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("GenomiX.Infrastructure.Models.GenUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GenomiX.Infrastructure.Models.DNAModel", b =>
                {
                    b.Navigation("DNAModelDiseases");

                    b.Navigation("Mutations");

                    b.Navigation("Sequences");
                });

            modelBuilder.Entity("GenomiX.Infrastructure.Models.Disease", b =>
                {
                    b.Navigation("DNAModelDiseases");
                });

            modelBuilder.Entity("GenomiX.Infrastructure.Models.GenUser", b =>
                {
                    b.Navigation("DNAModels");

                    b.Navigation("Lessons");

                    b.Navigation("Populations");
                });

            modelBuilder.Entity("GenomiX.Infrastructure.Models.Lesson", b =>
                {
                    b.Navigation("Tests");
                });

            modelBuilder.Entity("GenomiX.Infrastructure.Models.Population", b =>
                {
                    b.Navigation("Organisms");
                });

            modelBuilder.Entity("GenomiX.Infrastructure.Models.Question", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("GenomiX.Infrastructure.Models.Test", b =>
                {
                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
