// <auto-generated />
using System;
using GenomiX.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GenomiX.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GenomiX.Infrastructure.Models.Answer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Primary key (GUID).");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit")
                        .HasComment("Indicates whether the answer is correct.");

                    b.Property<Guid?>("QuestionId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("FK to Question.");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasComment("Answer text/value.");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Answers", t =>
                        {
                            t.HasComment("Answer option for a Test, with correctness flag.");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("b4f2f8a9-2a0a-4f67-9b2e-b7ac32af6242"),
                            IsCorrect = true,
                            QuestionId = new Guid("11111111-aaaa-2222-aaaa-aaaaaaaaaaaa"),
                            Value = "A pairs with T, C pairs with G"
                        },
                        new
                        {
                            Id = new Guid("c5e7c6e1-1bfc-4f7d-9f2a-8d2c6e0e8d9c"),
                            IsCorrect = false,
                            QuestionId = new Guid("11111111-aaaa-2222-aaaa-aaaaaaaaaaaa"),
                            Value = "A pairs with G, C pairs with T"
                        },
                        new
                        {
                            Id = new Guid("6a2f6f03-8a56-4a87-a2b9-33fc60a1b10f"),
                            IsCorrect = true,
                            QuestionId = new Guid("33333333-bbbb-4444-bbbb-bbbbbbbbbbbb"),
                            Value = "Changing a single base from A to G"
                        },
                        new
                        {
                            Id = new Guid("3d78217b-fb4a-4f64-80d1-1b9f408a64b2"),
                            IsCorrect = false,
                            QuestionId = new Guid("33333333-bbbb-4444-bbbb-bbbbbbbbbbbb"),
                            Value = "Removing a whole codon"
                        },
                        new
                        {
                            Id = new Guid("2d1c707f-43e9-43c2-8f20-dfb6c4140b1e"),
                            IsCorrect = true,
                            QuestionId = new Guid("55555555-cccc-6666-cccc-cccccccccccc"),
                            Value = "DNA ligase"
                        },
                        new
                        {
                            Id = new Guid("b69d2b41-8f21-47f6-9436-d2fc0e2c23b6"),
                            IsCorrect = false,
                            QuestionId = new Guid("55555555-cccc-6666-cccc-cccccccccccc"),
                            Value = "Amylase"
                        },
                        new
                        {
                            Id = new Guid("5b0c8cd4-9c26-46f0-94df-c36876ad6bc9"),
                            IsCorrect = true,
                            QuestionId = new Guid("77777777-dddd-8888-dddd-dddddddddddd"),
                            Value = "50"
                        },
                        new
                        {
                            Id = new Guid("1a5f8449-62a3-42e6-97e3-7c30c676890a"),
                            IsCorrect = false,
                            QuestionId = new Guid("77777777-dddd-8888-dddd-dddddddddddd"),
                            Value = "25"
                        },
                        new
                        {
                            Id = new Guid("14d6cb7b-44fa-40a6-a76f-657e7b9e8f95"),
                            IsCorrect = true,
                            QuestionId = new Guid("99999999-eeee-aaaa-eeee-eeeeeeeeeeee"),
                            Value = "Mutation"
                        },
                        new
                        {
                            Id = new Guid("26f84cf2-b33a-46f8-b1df-10f0c50bb979"),
                            IsCorrect = false,
                            QuestionId = new Guid("99999999-eeee-aaaa-eeee-eeeeeeeeeeee"),
                            Value = "Uniform environment"
                        });
                });

            modelBuilder.Entity("GenomiX.Infrastructure.Models.DNAModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Primary key (GUID).");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasComment("UTC created timestamp.");

                    b.Property<int>("CurrentIndex")
                        .HasColumnType("int")
                        .HasComment("Active timeline index (zero-based).");

                    b.Property<byte>("DisplayMode")
                        .HasColumnType("tinyint")
                        .HasComment("0 = Basic shapes, 1 = Scientific atomic view.");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasComment("UTC updated timestamp.");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Owner user (FK).");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("DNA_Models", t =>
                        {
                            t.HasComment("Editable DNA model holding references to two strand snapshots (double-helix).");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("44444444-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 6, 15, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CurrentIndex = 0,
                            DisplayMode = (byte)1,
                            UpdatedAt = new DateTimeOffset(new DateTime(2024, 6, 15, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UserId = new Guid("ea821ce2-2a3d-43ef-8978-5f34ee07d080")
                        },
                        new
                        {
                            Id = new Guid("44444444-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 7, 20, 9, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CurrentIndex = 0,
                            DisplayMode = (byte)0,
                            UpdatedAt = new DateTimeOffset(new DateTime(2024, 7, 20, 9, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UserId = new Guid("9d5e0ac1-4f1b-422b-b7f0-0f7d5d2dbbb1")
                        },
                        new
                        {
                            Id = new Guid("44444444-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 8, 25, 10, 45, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CurrentIndex = 0,
                            DisplayMode = (byte)1,
                            UpdatedAt = new DateTimeOffset(new DateTime(2024, 8, 25, 10, 45, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UserId = new Guid("58a7c2b5-1347-4f0a-b3ad-912d4f098aaa")
                        },
                        new
                        {
                            Id = new Guid("44444444-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 7, 20, 9, 5, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CurrentIndex = 0,
                            DisplayMode = (byte)1,
                            UpdatedAt = new DateTimeOffset(new DateTime(2024, 7, 20, 9, 5, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UserId = new Guid("a7f9a7d5-56f5-4f3f-8a9f-8c2f0d3d7001")
                        },
                        new
                        {
                            Id = new Guid("44444444-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 9, 10, 11, 20, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CurrentIndex = 0,
                            DisplayMode = (byte)1,
                            UpdatedAt = new DateTimeOffset(new DateTime(2024, 9, 10, 11, 20, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UserId = new Guid("c2b3d8ae-2b6d-4c41-9b8e-b1c2a3d4e005")
                        });
                });

            modelBuilder.Entity("GenomiX.Infrastructure.Models.DNAModelDisease", b =>
                {
                    b.Property<Guid>("DNAModelId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("FK to DNAModel.");

                    b.Property<Guid>("DiseaseId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("FK to Disease.");

                    b.HasKey("DNAModelId", "DiseaseId");

                    b.HasIndex("DiseaseId");

                    b.ToTable("DNA_Models_Diseases", t =>
                        {
                            t.HasComment("Many-to-many link between DNA models and diseases.");
                        });

                    b.HasData(
                        new
                        {
                            DNAModelId = new Guid("44444444-0000-0000-0000-000000000001"),
                            DiseaseId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            DNAModelId = new Guid("44444444-0000-0000-0000-000000000001"),
                            DiseaseId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            DNAModelId = new Guid("44444444-0000-0000-0000-000000000002"),
                            DiseaseId = new Guid("33333333-3333-3333-3333-333333333333")
                        });
                });

            modelBuilder.Entity("GenomiX.Infrastructure.Models.DNAModelMutation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Primary key (GUID).");

                    b.Property<string>("Alt")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasComment("Alternate bases inserted/replacing ref ('' allowed for deletion).");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasComment("UTC timestamp of the mutation record.");

                    b.Property<Guid?>("ModelId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("FK to DNAModel.");

                    b.Property<int>("PosEnd")
                        .HasColumnType("int")
                        .HasComment("1-based inclusive end position in the strand (>= PosStart).");

                    b.Property<int>("PosStart")
                        .HasColumnType("int")
                        .HasComment("1-based inclusive start position in the strand.");

                    b.Property<string>("Ref")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasComment("Reference bases being replaced/removed ('' allowed for insertion).");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasComment("Type of mutation: substitution | insertion | deletion.");

                    b.HasKey("Id");

                    b.HasIndex("ModelId");

                    b.ToTable("DNA_Model_Mutations", t =>
                        {
                            t.HasComment("Atomic edit to a DNAModel (substitution|insertion|deletion).");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-1111-1111-1111-aaaaaaaaaaaa"),
                            Alt = "T",
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 9, 1, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ModelId = new Guid("44444444-0000-0000-0000-000000000001"),
                            PosEnd = 6,
                            PosStart = 6,
                            Ref = "A",
                            Type = "substitution"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-2222-2222-2222-bbbbbbbbbbbb"),
                            Alt = "G",
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 9, 1, 10, 10, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ModelId = new Guid("44444444-0000-0000-0000-000000000001"),
                            PosEnd = 10,
                            PosStart = 10,
                            Ref = "",
                            Type = "insertion"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-3333-3333-3333-cccccccccccc"),
                            Alt = "",
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 9, 1, 10, 20, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ModelId = new Guid("44444444-0000-0000-0000-000000000002"),
                            PosEnd = 16,
                            PosStart = 15,
                            Ref = "CT",
                            Type = "deletion"
                        });
                });

            modelBuilder.Entity("GenomiX.Infrastructure.Models.DNASequence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Primary key (GUID).");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasComment("UTC timestamp when the snapshot was created.");

                    b.Property<Guid>("ModelId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Owning DNAModel (FK).");

                    b.Property<string>("Sequence")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Raw uppercase DNA string (A,C,G,T only).");

                    b.HasKey("Id");

                    b.HasIndex("ModelId");

                    b.ToTable("DNA_Sequences", t =>
                        {
                            t.HasComment("Immutable snapshot of a DNA sequence (A/C/G/T only).");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 6, 1, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ModelId = new Guid("44444444-0000-0000-0000-000000000001"),
                            Sequence = "ATGGTGCACCTGACTCCTGAGGAGAAGTCTGCCGTTACTGCCCTGTGGGGCAAGGTGAACGTGGATGAAGTTGGTGGTGAGGCCCTGGGCAG"
                        },
                        new
                        {
                            Id = new Guid("a2222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 6, 1, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ModelId = new Guid("44444444-0000-0000-0000-000000000001"),
                            Sequence = "TACACCACGTGGACTGAGACTCCTTTCAGACGGCAATGACGGGACACCCCGTTCCACTTGCACCTACTTCAACCACCACTCCGGGACCCGTC"
                        },
                        new
                        {
                            Id = new Guid("b1111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 7, 15, 10, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ModelId = new Guid("44444444-0000-0000-0000-000000000002"),
                            Sequence = "ATGGATGCCATGGGACCTGAGGAAGGAGAAGGCCCTGGGCCCTGAGGACCTTGGCTACACAGGCTGTTGGTGGTGCTGAGGAGGCTGGCCAC"
                        },
                        new
                        {
                            Id = new Guid("b2222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 7, 15, 10, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ModelId = new Guid("44444444-0000-0000-0000-000000000002"),
                            Sequence = "TACCTACGGTACCCTGGACTCCTTCCTCTTCCGGGACCCGGGACTCCTGGAACCGATGTGTCCGACAACCACCACGACTCCTCCGACCGGTG"
                        },
                        new
                        {
                            Id = new Guid("c1111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 8, 20, 8, 45, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ModelId = new Guid("44444444-0000-0000-0000-000000000003"),
                            Sequence = "ATGCCAGGAGCTGCTGGAGGAGGTGCTGGAGGCTGGAGGCGTTCCTGGGCTGAGTGGCTGGAGGAGGAGGAGCAGGAGGCTGGCTGCTGGAG"
                        },
                        new
                        {
                            Id = new Guid("c2222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 8, 20, 8, 45, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ModelId = new Guid("44444444-0000-0000-0000-000000000003"),
                            Sequence = "TACGGTCC TCGACGACCTCCTCCACGACCTCCGACCTCCGCAAGGACCCGACTCACCGACCTCCTCCTCGTCCTCCGACCGACGACCTC"
                        });
                });

            modelBuilder.Entity("GenomiX.Infrastructure.Models.Disease", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Primary key (GUID).");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)")
                        .HasComment("Optional description or summary.");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasComment("Disease name.");

                    b.HasKey("Id");

                    b.ToTable("Diseases", t =>
                        {
                            t.HasComment("Catalog of known diseases.");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Description = "Genetic disorder caused by a mutation in the HBB gene, leading to abnormal hemoglobin and sickle-shaped red blood cells.",
                            Name = "Sickle Cell Anemia"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Description = "Caused by mutations in the CFTR gene, resulting in thick mucus affecting the lungs and digestive system.",
                            Name = "Cystic Fibrosis"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Description = "Neurodegenerative disorder caused by expanded CAG repeats in the HTT gene.",
                            Name = "Huntington's Disease"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Description = "Metabolic disorder due to mutations in the PAH gene, leading to inability to break down phenylalanine.",
                            Name = "Phenylketonuria (PKU)"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Description = "Fatal genetic disorder caused by mutations in the HEXA gene, leading to accumulation of GM2 ganglioside in nerve cells.",
                            Name = "Tay-Sachs Disease"
                        });
                });

            modelBuilder.Entity("GenomiX.Infrastructure.Models.GenUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("ea821ce2-2a3d-43ef-8978-5f34ee07d080"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "11111111-1111-1111-1111-111111111111",
                            CreatedAt = new DateTime(2024, 6, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Email = "stilyan@example.com",
                            EmailConfirmed = true,
                            FirstName = "Stilyan",
                            LastName = "Chanev",
                            LockoutEnabled = false,
                            NormalizedEmail = "STILYAN@EXAMPLE.COM",
                            NormalizedUserName = "STILYAN",
                            PasswordHash = "AQAAAAIAAYagAAAAEHzs4+DPBZG9xAgWTlZ7ezRrWg2DfpAjDKOrzJizgKN9PduBps+Ke0JrDB5QNi5u/A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "aaaaaaa1-aaaa-aaaa-aaaa-aaaaaaaaaaaa",
                            TwoFactorEnabled = false,
                            UserName = "stilyan"
                        },
                        new
                        {
                            Id = new Guid("9d5e0ac1-4f1b-422b-b7f0-0f7d5d2dbbb1"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "22222222-2222-2222-2222-222222222222",
                            CreatedAt = new DateTime(2024, 7, 15, 10, 30, 0, 0, DateTimeKind.Utc),
                            Email = "alice@example.com",
                            EmailConfirmed = true,
                            FirstName = "Alice",
                            LastName = "Johnson",
                            LockoutEnabled = false,
                            NormalizedEmail = "ALICE@EXAMPLE.COM",
                            NormalizedUserName = "ALICE",
                            PasswordHash = "AQAAAAIAAYagAAAAED7CaPCa5Oa3vAGoXw8QDdC2aURdW1KhO/yY4ZEnWJoKpRjNUNu4dF9YLeIHByOjLg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "bbbbbbb2-bbbb-bbbb-bbbb-bbbbbbbbbbbb",
                            TwoFactorEnabled = false,
                            UserName = "alice"
                        },
                        new
                        {
                            Id = new Guid("58a7c2b5-1347-4f0a-b3ad-912d4f098aaa"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "33333333-3333-3333-3333-333333333333",
                            CreatedAt = new DateTime(2024, 8, 20, 8, 45, 0, 0, DateTimeKind.Utc),
                            Email = "ivan@example.com",
                            EmailConfirmed = false,
                            FirstName = "Ivan",
                            LastName = "Petrov",
                            LockoutEnabled = false,
                            NormalizedEmail = "IVAN@EXAMPLE.COM",
                            NormalizedUserName = "IVAN",
                            PasswordHash = "AQAAAAIAAYagAAAAEIkC1sWbH1iX8tcz2c1oRzFYI0J0mxPOhUkYqGp16wHQi0NmbTQd1+TquU5EtdISew==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ccccccc3-cccc-cccc-cccc-cccccccccccc",
                            TwoFactorEnabled = false,
                            UserName = "ivan"
                        },
                        new
                        {
                            Id = new Guid("a7f9a7d5-56f5-4f3f-8a9f-8c2f0d3d7001"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "44444444-4444-4444-4444-444444444444",
                            CreatedAt = new DateTime(2024, 7, 20, 9, 0, 0, 0, DateTimeKind.Utc),
                            Email = "maria.teacher@example.com",
                            EmailConfirmed = true,
                            FirstName = "Maria",
                            LastName = "Dimitrova",
                            LockoutEnabled = false,
                            NormalizedEmail = "MARIA.TEACHER@EXAMPLE.COM",
                            NormalizedUserName = "MARIA.TEACHER",
                            PasswordHash = "AQAAAAIAAYagAAAAEJ8JpK5Cz9z9qzQ2z5y0r8Zc8n5o3g9p+uZkqB5x0Gz3/7jZK3Tj3f1xY2nG8j0q5g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ddddddd4-dddd-dddd-dddd-dddddddddddd",
                            TwoFactorEnabled = false,
                            UserName = "maria.teacher"
                        },
                        new
                        {
                            Id = new Guid("c2b3d8ae-2b6d-4c41-9b8e-b1c2a3d4e005"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "55555555-5555-5555-5555-555555555555",
                            CreatedAt = new DateTime(2024, 9, 10, 11, 15, 0, 0, DateTimeKind.Utc),
                            Email = "georgi.scientist@example.com",
                            EmailConfirmed = true,
                            FirstName = "Georgi",
                            LastName = "Kolev",
                            LockoutEnabled = false,
                            NormalizedEmail = "GEORGI.SCIENTIST@EXAMPLE.COM",
                            NormalizedUserName = "GEORGI.SCIENTIST",
                            PasswordHash = "AQAAAAIAAYagAAAAEL6H2uXl7u0qg7c+W6ZQ2gk0q0zv2Qm8q6pA6xvYQ2n2eK1m8s0n1l5r3j0h2p4c6w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "eeeeeee5-eeee-eeee-eeee-eeeeeeeeeeee",
                            TwoFactorEnabled = false,
                            UserName = "georgi.scientist"
                        });
                });

            modelBuilder.Entity("GenomiX.Infrastructure.Models.Lesson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Primary key (GUID).");

                    b.Property<byte>("Difficulty")
                        .HasColumnType("tinyint")
                        .HasComment("Difficulty from 1 to 5.");

                    b.Property<string>("Information")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Markdown/HTML/plain content.");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("Lesson title.");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Topic (mutations, repair, probability, ...).");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("User who created the lesson.");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Lessons", t =>
                        {
                            t.HasComment("Lesson content for Education panel.");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaa1111-aaaa-1111-aaaa-aaaaaaaaaaaa"),
                            Difficulty = (byte)1,
                            Information = "DNA (Deoxyribonucleic acid) is a double helix composed of nucleotides: adenine (A), cytosine (C), guanine (G), and thymine (T). A pairs with T, and C pairs with G.",
                            Title = "DNA Structure Basics",
                            Topic = "DNA",
                            UserId = new Guid("a7f9a7d5-56f5-4f3f-8a9f-8c2f0d3d7001")
                        },
                        new
                        {
                            Id = new Guid("bbbb2222-bbbb-2222-bbbb-bbbbbbbbbbbb"),
                            Difficulty = (byte)2,
                            Information = "Mutations are changes in DNA. **Substitution** replaces one base, **insertion** adds bases, and **deletion** removes bases. Mutations can be harmful, neutral, or beneficial.",
                            Title = "Types of Mutations",
                            Topic = "Mutations",
                            UserId = new Guid("a7f9a7d5-56f5-4f3f-8a9f-8c2f0d3d7001")
                        },
                        new
                        {
                            Id = new Guid("cccc3333-cccc-3333-cccc-cccccccccccc"),
                            Difficulty = (byte)3,
                            Information = "Cells use repair mechanisms to fix DNA damage. Examples include mismatch repair, nucleotide excision repair, and double-strand break repair. Nanobot simulation in GenomiX demonstrates these concepts.",
                            Title = "DNA Repair Mechanisms",
                            Topic = "Repair",
                            UserId = new Guid("a7f9a7d5-56f5-4f3f-8a9f-8c2f0d3d7001")
                        },
                        new
                        {
                            Id = new Guid("dddd4444-dddd-4444-dddd-dddddddddddd"),
                            Difficulty = (byte)2,
                            Information = "Probability is key in genetics. For example, Punnett squares can predict the likelihood of offspring inheriting traits. The law of independent assortment applies.",
                            Title = "Probability in Genetics",
                            Topic = "Probability",
                            UserId = new Guid("a7f9a7d5-56f5-4f3f-8a9f-8c2f0d3d7001")
                        },
                        new
                        {
                            Id = new Guid("eeee5555-eeee-5555-eeee-eeeeeeeeeeee"),
                            Difficulty = (byte)4,
                            Information = "Populations evolve through natural selection, genetic drift, and gene flow. Environmental factors such as temperature or disease pressure influence survival.",
                            Title = "Population Evolution",
                            Topic = "Evolution",
                            UserId = new Guid("a7f9a7d5-56f5-4f3f-8a9f-8c2f0d3d7001")
                        });
                });

            modelBuilder.Entity("GenomiX.Infrastructure.Models.Organism", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Primary key (GUID).");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasComment("UTC created timestamp.");

                    b.Property<Guid?>("DNA_Sequence_Id")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("FK to a DNA strand snapshot (for this organism).");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("Optional description.");

                    b.Property<Guid?>("PopulationId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("FK to Population.");

                    b.Property<string>("ScientificName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasComment("Scientific-like identifier.");

                    b.Property<string>("SimpleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Simple/UI name.");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasComment("Status: alive | dead | reproduced.");

                    b.Property<double?>("SurvivalScore")
                        .HasColumnType("float")
                        .HasComment("Continuous survival/fitness score (nullable).");

                    b.HasKey("Id");

                    b.HasIndex("DNA_Sequence_Id");

                    b.HasIndex("PopulationId");

                    b.ToTable("Organisms");

                    b.HasData(
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 6, 1, 12, 5, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DNA_Sequence_Id = new Guid("a1111111-1111-1111-1111-111111111111"),
                            Description = "A simulated human organism from urban population.",
                            PopulationId = new Guid("11111111-1111-1111-1111-111111111111"),
                            ScientificName = "Homo sapiens A",
                            SimpleName = "Human A",
                            Status = "alive",
                            SurvivalScore = 0.84999999999999998
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 7, 15, 10, 35, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DNA_Sequence_Id = new Guid("a2222222-2222-2222-2222-222222222222"),
                            Description = "Lab mouse adapted to controlled temperature and low disease pressure.",
                            PopulationId = new Guid("22222222-2222-2222-2222-222222222222"),
                            ScientificName = "Mus musculus L1",
                            SimpleName = "Lab Mouse 1",
                            Status = "alive",
                            SurvivalScore = 0.92000000000000004
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 8, 20, 8, 50, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DNA_Sequence_Id = new Guid("b1111111-1111-1111-1111-111111111111"),
                            Description = "Leader of the wild dog pack, facing high disease pressure.",
                            PopulationId = new Guid("33333333-3333-3333-3333-333333333333"),
                            ScientificName = "Canis lupus familiaris Alpha",
                            SimpleName = "Dog Alpha",
                            Status = "alive",
                            SurvivalScore = 0.65000000000000002
                        });
                });

            modelBuilder.Entity("GenomiX.Infrastructure.Models.Population", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Primary key (GUID).");

                    b.Property<Guid?>("BaseModelId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Optional link to the base DNAModel used to derive this population.");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasComment("UTC created timestamp.");

                    b.Property<string>("Factors")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasComment("JSON with simulation factors (temperature, sunExposure, diseasePressure, ...).");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("Human-friendly name for the run.");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("User who created the population.");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Populations", t =>
                        {
                            t.HasComment("A population of organisms simulated under given environmental/selection factors.");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            BaseModelId = new Guid("44444444-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 6, 1, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Factors = "{ \"temperature\": 22, \"sunExposure\": \"medium\", \"diseasePressure\": 0.3 }",
                            Name = "Human Urban Population",
                            UserId = new Guid("ea821ce2-2a3d-43ef-8978-5f34ee07d080")
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            BaseModelId = new Guid("44444444-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 7, 15, 10, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Factors = "{ \"temperature\": 25, \"sunExposure\": \"low\", \"diseasePressure\": 0.1 }",
                            Name = "Mouse Lab Population",
                            UserId = new Guid("9d5e0ac1-4f1b-422b-b7f0-0f7d5d2dbbb1")
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            BaseModelId = new Guid("44444444-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 8, 20, 8, 45, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Factors = "{ \"temperature\": 28, \"sunExposure\": \"high\", \"diseasePressure\": 0.5 }",
                            Name = "Dog Wild Pack",
                            UserId = new Guid("58a7c2b5-1347-4f0a-b3ad-912d4f098aaa")
                        });
                });

            modelBuilder.Entity("GenomiX.Infrastructure.Models.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Primary key (GUID).");

                    b.Property<string>("Explanation")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)")
                        .HasComment("Optional explanation or hint for the question.");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasComment("The question text/prompt.");

                    b.Property<Guid?>("TestId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("FK to Test.");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasComment("Question type: mcq | multi | open.");

                    b.HasKey("Id");

                    b.HasIndex("TestId");

                    b.ToTable("Questions", t =>
                        {
                            t.HasComment("Question belonging to a Test, with prompt and possible answers.");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-aaaa-2222-aaaa-aaaaaaaaaaaa"),
                            Explanation = "Remember A pairs with T, and C pairs with G.",
                            Prompt = "Which bases pair together in DNA?",
                            TestId = new Guid("aaaa1111-aaaa-2222-aaaa-aaaaaaaaaaaa"),
                            Type = "mcq"
                        },
                        new
                        {
                            Id = new Guid("22222222-aaaa-3333-aaaa-aaaaaaaaaaaa"),
                            Explanation = "Think about the double structure.",
                            Prompt = "What shape does the DNA molecule form?",
                            TestId = new Guid("aaaa1111-aaaa-2222-aaaa-aaaaaaaaaaaa"),
                            Type = "open"
                        },
                        new
                        {
                            Id = new Guid("33333333-bbbb-4444-bbbb-bbbbbbbbbbbb"),
                            Prompt = "Which of the following is a substitution mutation?",
                            TestId = new Guid("bbbb2222-bbbb-3333-bbbb-bbbbbbbbbbbb"),
                            Type = "mcq"
                        },
                        new
                        {
                            Id = new Guid("44444444-bbbb-5555-bbbb-bbbbbbbbbbbb"),
                            Explanation = "There are more than one correct answers.",
                            Prompt = "Select all types of mutations.",
                            TestId = new Guid("bbbb2222-bbbb-3333-bbbb-bbbbbbbbbbbb"),
                            Type = "multi"
                        },
                        new
                        {
                            Id = new Guid("55555555-cccc-6666-cccc-cccccccccccc"),
                            Explanation = "Think about DNA polymerase and ligase.",
                            Prompt = "What enzyme is responsible for DNA repair?",
                            TestId = new Guid("cccc3333-cccc-4444-cccc-cccccccccccc"),
                            Type = "mcq"
                        },
                        new
                        {
                            Id = new Guid("66666666-cccc-7777-cccc-cccccccccccc"),
                            Explanation = "Short answer expected.",
                            Prompt = "Describe one method of DNA repair.",
                            TestId = new Guid("cccc3333-cccc-4444-cccc-cccccccccccc"),
                            Type = "open"
                        },
                        new
                        {
                            Id = new Guid("77777777-dddd-8888-dddd-dddddddddddd"),
                            Prompt = "If a trait has a probability of 25%, how many individuals out of 200 are expected to show it?",
                            TestId = new Guid("dddd4444-dddd-5555-dddd-dddddddddddd"),
                            Type = "mcq"
                        },
                        new
                        {
                            Id = new Guid("88888888-dddd-9999-dddd-dddddddddddd"),
                            Explanation = "Link probability rules to Punnett squares.",
                            Prompt = "Explain how probability affects inheritance in genetics.",
                            TestId = new Guid("dddd4444-dddd-5555-dddd-dddddddddddd"),
                            Type = "open"
                        },
                        new
                        {
                            Id = new Guid("99999999-eeee-aaaa-eeee-eeeeeeeeeeee"),
                            Explanation = "Think about recombination and mutation.",
                            Prompt = "Which factor increases genetic diversity in a population?",
                            TestId = new Guid("eeee5555-eeee-6666-eeee-eeeeeeeeeeee"),
                            Type = "mcq"
                        },
                        new
                        {
                            Id = new Guid("00000000-eeee-bbbb-eeee-eeeeeeeeeeee"),
                            Explanation = "Consider disease, climate, and mutation.",
                            Prompt = "Select all factors that influence population survival.",
                            TestId = new Guid("eeee5555-eeee-6666-eeee-eeeeeeeeeeee"),
                            Type = "multi"
                        });
                });

            modelBuilder.Entity("GenomiX.Infrastructure.Models.ReferenceSequence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Primary key (GUID).");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasComment("UTC timestamp when the reference sequence was created.");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("Descriptive name for the reference sequence (e.g., Beta-globin fragment).");

                    b.Property<int>("PairIndex")
                        .HasColumnType("int")
                        .HasComment("Pair index groups complementary strands together (e.g., 0 = initial pair).");

                    b.Property<string>("Sequence")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Raw uppercase DNA string (A,C,G,T only).");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Species or organism identifier for the reference sequence (e.g., Human, Mouse, Dog).");

                    b.Property<byte>("Strand")
                        .HasColumnType("tinyint")
                        .HasComment("Strand index of the reference sequence (1 = forward, 2 = complementary).");

                    b.HasKey("Id");

                    b.ToTable("Reference_Sequences", t =>
                        {
                            t.HasComment("Reference DNA sequence template (e.g., Human, Mouse, Dog). Not tied to a user.");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "BRCA1 fragment",
                            PairIndex = 0,
                            Sequence = "ATGGAAGAGCTGTCAGGAGAGCTGCCAGCTGGTGAGGAAGCAGTGAGCCTGAGCAAGAGCTGAG",
                            Species = "Homo sapiens",
                            Strand = (byte)1
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "BRCA1 fragment (complement)",
                            PairIndex = 0,
                            Sequence = "CTCAGCTCTTGCTCAGGCTCACTGCTTCCTCACCAGCTGGCAGCTCTCCTGACAGCTCTTCCAT",
                            Species = "Homo sapiens",
                            Strand = (byte)2
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "TP53 fragment",
                            PairIndex = 1,
                            Sequence = "ATGGTCAGGACCTGGAGAAGGAGCTGAGGCTGGATGAAGTCAAGAGTGTCAAGCGAGCTGAGG",
                            Species = "Mus musculus",
                            Strand = (byte)1
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "TP53 fragment (complement)",
                            PairIndex = 1,
                            Sequence = "CCTCAGCTCGCTTGACACTCTTGACTTCATCCAGCCTCAGCTCCTTCTCCAGGTCCTGACCAG",
                            Species = "Mus musculus",
                            Strand = (byte)2
                        },
                        new
                        {
                            Id = new Guid("33333333-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "COX1 mitochondrial fragment",
                            PairIndex = 2,
                            Sequence = "ATGGAAGAGGAGCTGCTGAGGAGCTGGTGAGGAAGCAGTGAGCCTGAGCAAGAGCTGAGCTA",
                            Species = "Canis lupus familiaris",
                            Strand = (byte)1
                        },
                        new
                        {
                            Id = new Guid("33333333-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "COX1 mitochondrial fragment (complement)",
                            PairIndex = 2,
                            Sequence = "TAGCTCAGCTCTTGCTCAGGCTCACTGCTTCCTCACCAGCTCCTCAGCAGCTCCTCTTCCAT",
                            Species = "Canis lupus familiaris",
                            Strand = (byte)2
                        });
                });

            modelBuilder.Entity("GenomiX.Infrastructure.Models.Test", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Primary key (GUID).");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("FK to Lesson.");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasComment("The title text.");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.ToTable("Tests", t =>
                        {
                            t.HasComment("Test/quiz question associated with a Lesson.");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaa1111-aaaa-2222-aaaa-aaaaaaaaaaaa"),
                            LessonId = new Guid("aaaa1111-aaaa-1111-aaaa-aaaaaaaaaaaa"),
                            Title = "Quiz: DNA Structure"
                        },
                        new
                        {
                            Id = new Guid("bbbb2222-bbbb-3333-bbbb-bbbbbbbbbbbb"),
                            LessonId = new Guid("bbbb2222-bbbb-2222-bbbb-bbbbbbbbbbbb"),
                            Title = "Quiz: Mutation Types"
                        },
                        new
                        {
                            Id = new Guid("cccc3333-cccc-4444-cccc-cccccccccccc"),
                            LessonId = new Guid("cccc3333-cccc-3333-cccc-cccccccccccc"),
                            Title = "Quiz: DNA Repair"
                        },
                        new
                        {
                            Id = new Guid("dddd4444-dddd-5555-dddd-dddddddddddd"),
                            LessonId = new Guid("dddd4444-dddd-4444-dddd-dddddddddddd"),
                            Title = "Quiz: Probability"
                        },
                        new
                        {
                            Id = new Guid("eeee5555-eeee-6666-eeee-eeeeeeeeeeee"),
                            LessonId = new Guid("eeee5555-eeee-5555-eeee-eeeeeeeeeeee"),
                            Title = "Quiz: Population Evolution"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("6e6f2c2a-7c3f-4e7d-9f84-2b3a4d9d1001"),
                            ConcurrencyStamp = "a1111111-aaaa-aaaa-aaaa-aaaaaaaaaaaa",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = new Guid("6e6f2c2a-7c3f-4e7d-9f84-2b3a4d9d1002"),
                            ConcurrencyStamp = "b2222222-bbbb-bbbb-bbbb-bbbbbbbbbbbb",
                            Name = "Student",
                            NormalizedName = "STUDENT"
                        },
                        new
                        {
                            Id = new Guid("6e6f2c2a-7c3f-4e7d-9f84-2b3a4d9d1003"),
                            ConcurrencyStamp = "c3333333-cccc-cccc-cccc-cccccccccccc",
                            Name = "Teacher",
                            NormalizedName = "TEACHER"
                        },
                        new
                        {
                            Id = new Guid("6e6f2c2a-7c3f-4e7d-9f84-2b3a4d9d1004"),
                            ConcurrencyStamp = "d4444444-dddd-dddd-dddd-dddddddddddd",
                            Name = "Scientist",
                            NormalizedName = "SCIENTIST"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("ea821ce2-2a3d-43ef-8978-5f34ee07d080"),
                            RoleId = new Guid("6e6f2c2a-7c3f-4e7d-9f84-2b3a4d9d1001")
                        },
                        new
                        {
                            UserId = new Guid("9d5e0ac1-4f1b-422b-b7f0-0f7d5d2dbbb1"),
                            RoleId = new Guid("6e6f2c2a-7c3f-4e7d-9f84-2b3a4d9d1002")
                        },
                        new
                        {
                            UserId = new Guid("58a7c2b5-1347-4f0a-b3ad-912d4f098aaa"),
                            RoleId = new Guid("6e6f2c2a-7c3f-4e7d-9f84-2b3a4d9d1002")
                        },
                        new
                        {
                            UserId = new Guid("a7f9a7d5-56f5-4f3f-8a9f-8c2f0d3d7001"),
                            RoleId = new Guid("6e6f2c2a-7c3f-4e7d-9f84-2b3a4d9d1003")
                        },
                        new
                        {
                            UserId = new Guid("c2b3d8ae-2b6d-4c41-9b8e-b1c2a3d4e005"),
                            RoleId = new Guid("6e6f2c2a-7c3f-4e7d-9f84-2b3a4d9d1004")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("GenomiX.Infrastructure.Models.Answer", b =>
                {
                    b.HasOne("GenomiX.Infrastructure.Models.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("GenomiX.Infrastructure.Models.DNAModel", b =>
                {
                    b.HasOne("GenomiX.Infrastructure.Models.GenUser", "User")
                        .WithMany("DNAModels")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GenomiX.Infrastructure.Models.DNAModelDisease", b =>
                {
                    b.HasOne("GenomiX.Infrastructure.Models.DNAModel", null)
                        .WithMany("DNAModelDiseases")
                        .HasForeignKey("DNAModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GenomiX.Infrastructure.Models.Disease", null)
                        .WithMany("DNAModelDiseases")
                        .HasForeignKey("DiseaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GenomiX.Infrastructure.Models.DNAModelMutation", b =>
                {
                    b.HasOne("GenomiX.Infrastructure.Models.DNAModel", "Model")
                        .WithMany("Mutations")
                        .HasForeignKey("ModelId");

                    b.Navigation("Model");
                });

            modelBuilder.Entity("GenomiX.Infrastructure.Models.DNASequence", b =>
                {
                    b.HasOne("GenomiX.Infrastructure.Models.DNAModel", "Model")
                        .WithMany("Sequences")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Model");
                });

            modelBuilder.Entity("GenomiX.Infrastructure.Models.Lesson", b =>
                {
                    b.HasOne("GenomiX.Infrastructure.Models.GenUser", "User")
                        .WithMany("Lessons")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GenomiX.Infrastructure.Models.Organism", b =>
                {
                    b.HasOne("GenomiX.Infrastructure.Models.DNASequence", "DNASequence")
                        .WithMany()
                        .HasForeignKey("DNA_Sequence_Id");

                    b.HasOne("GenomiX.Infrastructure.Models.Population", "Population")
                        .WithMany("Organisms")
                        .HasForeignKey("PopulationId");

                    b.Navigation("DNASequence");

                    b.Navigation("Population");
                });

            modelBuilder.Entity("GenomiX.Infrastructure.Models.Population", b =>
                {
                    b.HasOne("GenomiX.Infrastructure.Models.GenUser", "User")
                        .WithMany("Populations")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GenomiX.Infrastructure.Models.Question", b =>
                {
                    b.HasOne("GenomiX.Infrastructure.Models.Test", "Test")
                        .WithMany("Questions")
                        .HasForeignKey("TestId");

                    b.Navigation("Test");
                });

            modelBuilder.Entity("GenomiX.Infrastructure.Models.Test", b =>
                {
                    b.HasOne("GenomiX.Infrastructure.Models.Lesson", null)
                        .WithMany("Tests")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("GenomiX.Infrastructure.Models.GenUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("GenomiX.Infrastructure.Models.GenUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GenomiX.Infrastructure.Models.GenUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("GenomiX.Infrastructure.Models.GenUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GenomiX.Infrastructure.Models.DNAModel", b =>
                {
                    b.Navigation("DNAModelDiseases");

                    b.Navigation("Mutations");

                    b.Navigation("Sequences");
                });

            modelBuilder.Entity("GenomiX.Infrastructure.Models.Disease", b =>
                {
                    b.Navigation("DNAModelDiseases");
                });

            modelBuilder.Entity("GenomiX.Infrastructure.Models.GenUser", b =>
                {
                    b.Navigation("DNAModels");

                    b.Navigation("Lessons");

                    b.Navigation("Populations");
                });

            modelBuilder.Entity("GenomiX.Infrastructure.Models.Lesson", b =>
                {
                    b.Navigation("Tests");
                });

            modelBuilder.Entity("GenomiX.Infrastructure.Models.Population", b =>
                {
                    b.Navigation("Organisms");
                });

            modelBuilder.Entity("GenomiX.Infrastructure.Models.Question", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("GenomiX.Infrastructure.Models.Test", b =>
                {
                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
